### ISSUE TITLE
Enviar mensagens sequencialmente

### ISSUE THREAD

**Issue by Windows87** [douglasjunior/react-native-easybluetooth-le#4]
Olá Douglas,
  Tenho uma dúvida, e ela é mais relacionada ao Bluetooth do que do que a biblioteca mesmo. Eu quero mandar mensagens sequencialmente, por exemplo:

```javascript
  componentDidMount() {
  	this.sendMessages();
  }

  sendMessages = async () => {
  	try {
  	  await EasyBluetooth.writeln('aaaaaaaaaa');
  	  await EasyBluetooth.writeln('bb');
  	  await EasyBluetooth.writeln('ccccccccc');
  	  await EasyBluetooth.writeln('dd');
  	  await EasyBluetooth.writeln('eeeeeeeeeeeeeeee');
  	  await EasyBluetooth.writeln('ffffffffff');
  	  await EasyBluetooth.writeln('ggggg');
  	} catch(error) {
          console.log(error);
  	  ToastAndroid.show('Error on send Message', ToastAndroid.SHORT);
  	}
  }
```

mas quando eu vou usar o Bluetooth junto com o Arduino Uno e estou usando um código mais complexo (estou usando 89% da memória dinâmica e 47% de armazenamento), ele recebe mensagens diferentes (ou até faltando alguma mensagem), por exemplo:

```
aaaaaaaaaa
aaaaaaaaaa
bbbb
cccccccccdd
eeeeeeeeeeeeeee
ffffffffff
ggggg  
```

Minha dúvida é: como posso minimizar esses erros? Enviar duas mensagens seguidas está tudo bem, o problema é quando uma mensagem se junta com a outra ou o Bluetooth não recebe ela.

Devo colocar um delay antes de mandar a próxima mensagem, mudar o Baud Rate do Bluetooth ou alguma outra coisa? Valeu!

**Comment by douglasjunior** [comment]
Oi @Windows87, se você já tem todas as informações que precisa enviar, acho que você poderia concatenar as Strings e mandar tudo de uma vez.

```js
          const message = 'aaaaaaaaaa\n'
                      + 'bb\n'
                      + 'ccccccccc\n'
                      + '...';
  	  await EasyBluetooth.writeln(message);
```

Por outro lado, acho que aumentar o baudrate ou colocar um delay talvez ajude. Se vc enviar "muito rápido" pode acontecer do Arduino não conseguir segurar o buffer e descartar a informação antes de ler completamente.

Eu nunca trabalhei sério com Arduino, sempre com implementações utilizando hardware customizado, então normalmente os devs do hardware eram quem se preocupavam mais com essas questões.

**Comment by Windows87** [comment]
Vou tentar mandar tudo de uma vez então e colocar um delay antes de enviar a próxima mensagem também.
Valeu @douglasjunior
